# Generated by Django 3.2.18 on 2023-03-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descripcion', models.TextField()),
                ('proveedor', models.CharField(max_length=100)),
                ('beneficios', models.TextField()),
                ('stock', models.IntegerField()),
                ('foto', models.CharField(max_length=200)),
            ],
        ),
    ]
